version: "3"
services:
  ddbb:
    image: jmsanchez/oracle-21-ee-outbox
    expose:
      - 1521
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD-SHELL", "fuser 1521/tcp" ]
  zookeeper:
    build: .
    entrypoint: ./bin/zookeeper-server-start.sh ./config/zookeeper.properties
    expose: 
       - 2181
    ports:
       - "2181:2181"
  kafka:
    build: .
    entrypoint: ./bin/kafka-server-start.sh ./config/server.properties
    expose: 
       - 9092
    ports:
       - "9092:9092"
    depends_on: 
       - zookeeper
  connect:
    build: .
    environment:
      - CLASSPATH=/opt/connect/*
    entrypoint: ./bin/connect-standalone.sh /opt/connect/config/connect-standalone.properties /opt/connect/config/connect-jambo-outbox.properties
    volumes:
        - ./target:/opt/connect
        - ./config:/opt/connect/config
    depends_on:
       - kafka
       - ddbb

