CREATE SEQUENCE JAMBO.SEQ_OUTBOX_ID INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE TABLE JAMBO.OUTBOX
   (
    "ID" NUMBER(28,0) DEFAULT SEQ_OUTBOX_ID.nextVal PRIMARY KEY,
    "EVENT_ID" VARCHAR2(200 CHAR) NOT NULL,
    "EVENT_TYPE" VARCHAR2(200 CHAR) NOT NULL,
    "CREATE_AT" DATE DEFAULT SYSDATE,
    "KEY" VARCHAR2(100 CHAR),
    "DATA" CLOB NOT NULL
   );